title: AR/VR Technology Overview
pages:
  - title: Introduction of Technology
    filename: introduction.html
  - title: Real-World Examples
    filename: examples.html
  - title: Social Implications
    filename: social_implications.html
  - title: Mitigating Harms
    filename: mitigating_harms.html
